# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phas', '0002_auto_20171025_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pha',
            name='county',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
